app:
  cors:
    origin: 'https://smartspec.example.com'
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    credentials: true

openai:
  model: 'gpt-4'
  temperature: 0.5
  maxTokens: 4000
  timeout: 60000

qdrant:
  url: 'https://qdrant.production:6333'
  collections:
    initiatives: 'initiatives'
    tasks: 'tasks'
  dimensions: 1536
  distance: 'Cosine'

metrics:
  enabled: true
  prefix: 'smartspec_'
  defaultLabels:
    app: 'smartspec'
    env: 'production'

logging:
  level: 'info'
  format: 'json'
  pretty: false
